// proto/order.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: internal/adapters/grpc/proto/order.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_internal_adapters_grpc_proto_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_adapters_grpc_proto_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_internal_adapters_grpc_proto_order_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenType     string                 `protobuf:"bytes,1,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`
	ExpiresIn     int64                  `protobuf:"varint,2,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	AccessToken   string                 `protobuf:"bytes,3,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,4,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	Type          string                 `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
	Code          int32                  `protobuf:"varint,7,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_internal_adapters_grpc_proto_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_adapters_grpc_proto_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_internal_adapters_grpc_proto_order_proto_rawDescGZIP(), []int{1}
}

func (x *LoginResponse) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

func (x *LoginResponse) GetExpiresIn() int64 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

func (x *LoginResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LoginResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *LoginResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LoginResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *LoginResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type CreateOrderRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	StoreId            int64                  `protobuf:"varint,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	MerchantOrderId    string                 `protobuf:"bytes,2,opt,name=merchant_order_id,json=merchantOrderId,proto3" json:"merchant_order_id,omitempty"`
	RecipientName      string                 `protobuf:"bytes,3,opt,name=recipient_name,json=recipientName,proto3" json:"recipient_name,omitempty"`
	RecipientPhone     string                 `protobuf:"bytes,4,opt,name=recipient_phone,json=recipientPhone,proto3" json:"recipient_phone,omitempty"`
	RecipientAddress   string                 `protobuf:"bytes,5,opt,name=recipient_address,json=recipientAddress,proto3" json:"recipient_address,omitempty"`
	RecipientCity      int64                  `protobuf:"varint,6,opt,name=recipient_city,json=recipientCity,proto3" json:"recipient_city,omitempty"`
	RecipientZone      int64                  `protobuf:"varint,7,opt,name=recipient_zone,json=recipientZone,proto3" json:"recipient_zone,omitempty"`
	RecipientArea      int64                  `protobuf:"varint,8,opt,name=recipient_area,json=recipientArea,proto3" json:"recipient_area,omitempty"`
	DeliveryType       int64                  `protobuf:"varint,9,opt,name=delivery_type,json=deliveryType,proto3" json:"delivery_type,omitempty"`
	ItemType           int64                  `protobuf:"varint,10,opt,name=item_type,json=itemType,proto3" json:"item_type,omitempty"`
	SpecialInstruction string                 `protobuf:"bytes,11,opt,name=special_instruction,json=specialInstruction,proto3" json:"special_instruction,omitempty"`
	ItemQuantity       int64                  `protobuf:"varint,12,opt,name=item_quantity,json=itemQuantity,proto3" json:"item_quantity,omitempty"`
	ItemWeight         float64                `protobuf:"fixed64,13,opt,name=item_weight,json=itemWeight,proto3" json:"item_weight,omitempty"`
	AmountToCollect    float64                `protobuf:"fixed64,14,opt,name=amount_to_collect,json=amountToCollect,proto3" json:"amount_to_collect,omitempty"`
	ItemDescription    string                 `protobuf:"bytes,15,opt,name=item_description,json=itemDescription,proto3" json:"item_description,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_internal_adapters_grpc_proto_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_adapters_grpc_proto_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_internal_adapters_grpc_proto_order_proto_rawDescGZIP(), []int{2}
}

func (x *CreateOrderRequest) GetStoreId() int64 {
	if x != nil {
		return x.StoreId
	}
	return 0
}

func (x *CreateOrderRequest) GetMerchantOrderId() string {
	if x != nil {
		return x.MerchantOrderId
	}
	return ""
}

func (x *CreateOrderRequest) GetRecipientName() string {
	if x != nil {
		return x.RecipientName
	}
	return ""
}

func (x *CreateOrderRequest) GetRecipientPhone() string {
	if x != nil {
		return x.RecipientPhone
	}
	return ""
}

func (x *CreateOrderRequest) GetRecipientAddress() string {
	if x != nil {
		return x.RecipientAddress
	}
	return ""
}

func (x *CreateOrderRequest) GetRecipientCity() int64 {
	if x != nil {
		return x.RecipientCity
	}
	return 0
}

func (x *CreateOrderRequest) GetRecipientZone() int64 {
	if x != nil {
		return x.RecipientZone
	}
	return 0
}

func (x *CreateOrderRequest) GetRecipientArea() int64 {
	if x != nil {
		return x.RecipientArea
	}
	return 0
}

func (x *CreateOrderRequest) GetDeliveryType() int64 {
	if x != nil {
		return x.DeliveryType
	}
	return 0
}

func (x *CreateOrderRequest) GetItemType() int64 {
	if x != nil {
		return x.ItemType
	}
	return 0
}

func (x *CreateOrderRequest) GetSpecialInstruction() string {
	if x != nil {
		return x.SpecialInstruction
	}
	return ""
}

func (x *CreateOrderRequest) GetItemQuantity() int64 {
	if x != nil {
		return x.ItemQuantity
	}
	return 0
}

func (x *CreateOrderRequest) GetItemWeight() float64 {
	if x != nil {
		return x.ItemWeight
	}
	return 0
}

func (x *CreateOrderRequest) GetAmountToCollect() float64 {
	if x != nil {
		return x.AmountToCollect
	}
	return 0
}

func (x *CreateOrderRequest) GetItemDescription() string {
	if x != nil {
		return x.ItemDescription
	}
	return ""
}

type CreateOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Code          int32                  `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
	Data          *OrderData             `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderResponse) Reset() {
	*x = CreateOrderResponse{}
	mi := &file_internal_adapters_grpc_proto_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderResponse) ProtoMessage() {}

func (x *CreateOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_adapters_grpc_proto_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderResponse.ProtoReflect.Descriptor instead.
func (*CreateOrderResponse) Descriptor() ([]byte, []int) {
	return file_internal_adapters_grpc_proto_order_proto_rawDescGZIP(), []int{3}
}

func (x *CreateOrderResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateOrderResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateOrderResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CreateOrderResponse) GetData() *OrderData {
	if x != nil {
		return x.Data
	}
	return nil
}

type OrderData struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ConsignmentId   string                 `protobuf:"bytes,1,opt,name=consignment_id,json=consignmentId,proto3" json:"consignment_id,omitempty"`
	MerchantOrderId string                 `protobuf:"bytes,2,opt,name=merchant_order_id,json=merchantOrderId,proto3" json:"merchant_order_id,omitempty"`
	OrderStatus     string                 `protobuf:"bytes,3,opt,name=order_status,json=orderStatus,proto3" json:"order_status,omitempty"`
	DeliveryFee     float64                `protobuf:"fixed64,4,opt,name=delivery_fee,json=deliveryFee,proto3" json:"delivery_fee,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *OrderData) Reset() {
	*x = OrderData{}
	mi := &file_internal_adapters_grpc_proto_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderData) ProtoMessage() {}

func (x *OrderData) ProtoReflect() protoreflect.Message {
	mi := &file_internal_adapters_grpc_proto_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderData.ProtoReflect.Descriptor instead.
func (*OrderData) Descriptor() ([]byte, []int) {
	return file_internal_adapters_grpc_proto_order_proto_rawDescGZIP(), []int{4}
}

func (x *OrderData) GetConsignmentId() string {
	if x != nil {
		return x.ConsignmentId
	}
	return ""
}

func (x *OrderData) GetMerchantOrderId() string {
	if x != nil {
		return x.MerchantOrderId
	}
	return ""
}

func (x *OrderData) GetOrderStatus() string {
	if x != nil {
		return x.OrderStatus
	}
	return ""
}

func (x *OrderData) GetDeliveryFee() float64 {
	if x != nil {
		return x.DeliveryFee
	}
	return 0
}

type ListOrdersRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TransferStatus int64                  `protobuf:"varint,1,opt,name=transfer_status,json=transferStatus,proto3" json:"transfer_status,omitempty"`
	Archive        int64                  `protobuf:"varint,2,opt,name=archive,proto3" json:"archive,omitempty"`
	Limit          int64                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Page           int64                  `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListOrdersRequest) Reset() {
	*x = ListOrdersRequest{}
	mi := &file_internal_adapters_grpc_proto_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersRequest) ProtoMessage() {}

func (x *ListOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_adapters_grpc_proto_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersRequest.ProtoReflect.Descriptor instead.
func (*ListOrdersRequest) Descriptor() ([]byte, []int) {
	return file_internal_adapters_grpc_proto_order_proto_rawDescGZIP(), []int{5}
}

func (x *ListOrdersRequest) GetTransferStatus() int64 {
	if x != nil {
		return x.TransferStatus
	}
	return 0
}

func (x *ListOrdersRequest) GetArchive() int64 {
	if x != nil {
		return x.Archive
	}
	return 0
}

func (x *ListOrdersRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListOrdersRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

type ListOrdersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Code          int32                  `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
	Data          *OrdersData            `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersResponse) Reset() {
	*x = ListOrdersResponse{}
	mi := &file_internal_adapters_grpc_proto_order_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersResponse) ProtoMessage() {}

func (x *ListOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_adapters_grpc_proto_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersResponse.ProtoReflect.Descriptor instead.
func (*ListOrdersResponse) Descriptor() ([]byte, []int) {
	return file_internal_adapters_grpc_proto_order_proto_rawDescGZIP(), []int{6}
}

func (x *ListOrdersResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ListOrdersResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ListOrdersResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ListOrdersResponse) GetData() *OrdersData {
	if x != nil {
		return x.Data
	}
	return nil
}

type OrdersData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*Order               `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	CurrentPage   int64                  `protobuf:"varint,3,opt,name=current_page,json=currentPage,proto3" json:"current_page,omitempty"`
	PerPage       int64                  `protobuf:"varint,4,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	TotalInPage   int64                  `protobuf:"varint,5,opt,name=total_in_page,json=totalInPage,proto3" json:"total_in_page,omitempty"`
	LastPage      int64                  `protobuf:"varint,6,opt,name=last_page,json=lastPage,proto3" json:"last_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrdersData) Reset() {
	*x = OrdersData{}
	mi := &file_internal_adapters_grpc_proto_order_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrdersData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrdersData) ProtoMessage() {}

func (x *OrdersData) ProtoReflect() protoreflect.Message {
	mi := &file_internal_adapters_grpc_proto_order_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrdersData.ProtoReflect.Descriptor instead.
func (*OrdersData) Descriptor() ([]byte, []int) {
	return file_internal_adapters_grpc_proto_order_proto_rawDescGZIP(), []int{7}
}

func (x *OrdersData) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

func (x *OrdersData) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *OrdersData) GetCurrentPage() int64 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *OrdersData) GetPerPage() int64 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

func (x *OrdersData) GetTotalInPage() int64 {
	if x != nil {
		return x.TotalInPage
	}
	return 0
}

func (x *OrdersData) GetLastPage() int64 {
	if x != nil {
		return x.LastPage
	}
	return 0
}

type Order struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	OrderConsignmentId string                 `protobuf:"bytes,1,opt,name=order_consignment_id,json=orderConsignmentId,proto3" json:"order_consignment_id,omitempty"`
	OrderCreatedAt     string                 `protobuf:"bytes,2,opt,name=order_created_at,json=orderCreatedAt,proto3" json:"order_created_at,omitempty"`
	OrderDescription   string                 `protobuf:"bytes,3,opt,name=order_description,json=orderDescription,proto3" json:"order_description,omitempty"`
	MerchantOrderId    string                 `protobuf:"bytes,4,opt,name=merchant_order_id,json=merchantOrderId,proto3" json:"merchant_order_id,omitempty"`
	RecipientName      string                 `protobuf:"bytes,5,opt,name=recipient_name,json=recipientName,proto3" json:"recipient_name,omitempty"`
	RecipientAddress   string                 `protobuf:"bytes,6,opt,name=recipient_address,json=recipientAddress,proto3" json:"recipient_address,omitempty"`
	RecipientPhone     string                 `protobuf:"bytes,7,opt,name=recipient_phone,json=recipientPhone,proto3" json:"recipient_phone,omitempty"`
	OrderAmount        float64                `protobuf:"fixed64,8,opt,name=order_amount,json=orderAmount,proto3" json:"order_amount,omitempty"`
	TotalFee           float64                `protobuf:"fixed64,9,opt,name=total_fee,json=totalFee,proto3" json:"total_fee,omitempty"`
	Instruction        string                 `protobuf:"bytes,10,opt,name=instruction,proto3" json:"instruction,omitempty"`
	OrderTypeId        int64                  `protobuf:"varint,11,opt,name=order_type_id,json=orderTypeId,proto3" json:"order_type_id,omitempty"`
	CodFee             float64                `protobuf:"fixed64,12,opt,name=cod_fee,json=codFee,proto3" json:"cod_fee,omitempty"`
	PromoDiscount      float64                `protobuf:"fixed64,13,opt,name=promo_discount,json=promoDiscount,proto3" json:"promo_discount,omitempty"`
	Discount           float64                `protobuf:"fixed64,14,opt,name=discount,proto3" json:"discount,omitempty"`
	DeliveryFee        float64                `protobuf:"fixed64,15,opt,name=delivery_fee,json=deliveryFee,proto3" json:"delivery_fee,omitempty"`
	OrderStatus        string                 `protobuf:"bytes,16,opt,name=order_status,json=orderStatus,proto3" json:"order_status,omitempty"`
	OrderType          string                 `protobuf:"bytes,17,opt,name=order_type,json=orderType,proto3" json:"order_type,omitempty"`
	ItemType           int64                  `protobuf:"varint,18,opt,name=item_type,json=itemType,proto3" json:"item_type,omitempty"`
	StoreName          string                 `protobuf:"bytes,19,opt,name=store_name,json=storeName,proto3" json:"store_name,omitempty"`
	StoreContactPhone  string                 `protobuf:"bytes,20,opt,name=store_contact_phone,json=storeContactPhone,proto3" json:"store_contact_phone,omitempty"`
	CodAmount          float64                `protobuf:"fixed64,21,opt,name=cod_amount,json=codAmount,proto3" json:"cod_amount,omitempty"`
	DeliveryCharge     float64                `protobuf:"fixed64,22,opt,name=delivery_charge,json=deliveryCharge,proto3" json:"delivery_charge,omitempty"`
	StoreId            int64                  `protobuf:"varint,23,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	RecipientCity      int64                  `protobuf:"varint,24,opt,name=recipient_city,json=recipientCity,proto3" json:"recipient_city,omitempty"`
	RecipientZone      int64                  `protobuf:"varint,25,opt,name=recipient_zone,json=recipientZone,proto3" json:"recipient_zone,omitempty"`
	RecipientArea      int64                  `protobuf:"varint,26,opt,name=recipient_area,json=recipientArea,proto3" json:"recipient_area,omitempty"`
	DeliveryType       int64                  `protobuf:"varint,27,opt,name=delivery_type,json=deliveryType,proto3" json:"delivery_type,omitempty"`
	ItemQuantity       int64                  `protobuf:"varint,28,opt,name=item_quantity,json=itemQuantity,proto3" json:"item_quantity,omitempty"`
	ItemWeight         float64                `protobuf:"fixed64,29,opt,name=item_weight,json=itemWeight,proto3" json:"item_weight,omitempty"`
	AmountToCollect    float64                `protobuf:"fixed64,30,opt,name=amount_to_collect,json=amountToCollect,proto3" json:"amount_to_collect,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_internal_adapters_grpc_proto_order_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_internal_adapters_grpc_proto_order_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_internal_adapters_grpc_proto_order_proto_rawDescGZIP(), []int{8}
}

func (x *Order) GetOrderConsignmentId() string {
	if x != nil {
		return x.OrderConsignmentId
	}
	return ""
}

func (x *Order) GetOrderCreatedAt() string {
	if x != nil {
		return x.OrderCreatedAt
	}
	return ""
}

func (x *Order) GetOrderDescription() string {
	if x != nil {
		return x.OrderDescription
	}
	return ""
}

func (x *Order) GetMerchantOrderId() string {
	if x != nil {
		return x.MerchantOrderId
	}
	return ""
}

func (x *Order) GetRecipientName() string {
	if x != nil {
		return x.RecipientName
	}
	return ""
}

func (x *Order) GetRecipientAddress() string {
	if x != nil {
		return x.RecipientAddress
	}
	return ""
}

func (x *Order) GetRecipientPhone() string {
	if x != nil {
		return x.RecipientPhone
	}
	return ""
}

func (x *Order) GetOrderAmount() float64 {
	if x != nil {
		return x.OrderAmount
	}
	return 0
}

func (x *Order) GetTotalFee() float64 {
	if x != nil {
		return x.TotalFee
	}
	return 0
}

func (x *Order) GetInstruction() string {
	if x != nil {
		return x.Instruction
	}
	return ""
}

func (x *Order) GetOrderTypeId() int64 {
	if x != nil {
		return x.OrderTypeId
	}
	return 0
}

func (x *Order) GetCodFee() float64 {
	if x != nil {
		return x.CodFee
	}
	return 0
}

func (x *Order) GetPromoDiscount() float64 {
	if x != nil {
		return x.PromoDiscount
	}
	return 0
}

func (x *Order) GetDiscount() float64 {
	if x != nil {
		return x.Discount
	}
	return 0
}

func (x *Order) GetDeliveryFee() float64 {
	if x != nil {
		return x.DeliveryFee
	}
	return 0
}

func (x *Order) GetOrderStatus() string {
	if x != nil {
		return x.OrderStatus
	}
	return ""
}

func (x *Order) GetOrderType() string {
	if x != nil {
		return x.OrderType
	}
	return ""
}

func (x *Order) GetItemType() int64 {
	if x != nil {
		return x.ItemType
	}
	return 0
}

func (x *Order) GetStoreName() string {
	if x != nil {
		return x.StoreName
	}
	return ""
}

func (x *Order) GetStoreContactPhone() string {
	if x != nil {
		return x.StoreContactPhone
	}
	return ""
}

func (x *Order) GetCodAmount() float64 {
	if x != nil {
		return x.CodAmount
	}
	return 0
}

func (x *Order) GetDeliveryCharge() float64 {
	if x != nil {
		return x.DeliveryCharge
	}
	return 0
}

func (x *Order) GetStoreId() int64 {
	if x != nil {
		return x.StoreId
	}
	return 0
}

func (x *Order) GetRecipientCity() int64 {
	if x != nil {
		return x.RecipientCity
	}
	return 0
}

func (x *Order) GetRecipientZone() int64 {
	if x != nil {
		return x.RecipientZone
	}
	return 0
}

func (x *Order) GetRecipientArea() int64 {
	if x != nil {
		return x.RecipientArea
	}
	return 0
}

func (x *Order) GetDeliveryType() int64 {
	if x != nil {
		return x.DeliveryType
	}
	return 0
}

func (x *Order) GetItemQuantity() int64 {
	if x != nil {
		return x.ItemQuantity
	}
	return 0
}

func (x *Order) GetItemWeight() float64 {
	if x != nil {
		return x.ItemWeight
	}
	return 0
}

func (x *Order) GetAmountToCollect() float64 {
	if x != nil {
		return x.AmountToCollect
	}
	return 0
}

type CancelOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConsignmentId string                 `protobuf:"bytes,1,opt,name=consignment_id,json=consignmentId,proto3" json:"consignment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderRequest) Reset() {
	*x = CancelOrderRequest{}
	mi := &file_internal_adapters_grpc_proto_order_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderRequest) ProtoMessage() {}

func (x *CancelOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_adapters_grpc_proto_order_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderRequest.ProtoReflect.Descriptor instead.
func (*CancelOrderRequest) Descriptor() ([]byte, []int) {
	return file_internal_adapters_grpc_proto_order_proto_rawDescGZIP(), []int{9}
}

func (x *CancelOrderRequest) GetConsignmentId() string {
	if x != nil {
		return x.ConsignmentId
	}
	return ""
}

type CancelOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Code          int32                  `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderResponse) Reset() {
	*x = CancelOrderResponse{}
	mi := &file_internal_adapters_grpc_proto_order_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderResponse) ProtoMessage() {}

func (x *CancelOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_adapters_grpc_proto_order_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderResponse.ProtoReflect.Descriptor instead.
func (*CancelOrderResponse) Descriptor() ([]byte, []int) {
	return file_internal_adapters_grpc_proto_order_proto_rawDescGZIP(), []int{10}
}

func (x *CancelOrderResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CancelOrderResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CancelOrderResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_internal_adapters_grpc_proto_order_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_adapters_grpc_proto_order_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_internal_adapters_grpc_proto_order_proto_rawDescGZIP(), []int{11}
}

type LogoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Code          int32                  `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutResponse) Reset() {
	*x = LogoutResponse{}
	mi := &file_internal_adapters_grpc_proto_order_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutResponse) ProtoMessage() {}

func (x *LogoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_adapters_grpc_proto_order_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutResponse.ProtoReflect.Descriptor instead.
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return file_internal_adapters_grpc_proto_order_proto_rawDescGZIP(), []int{12}
}

func (x *LogoutResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogoutResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *LogoutResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

var File_internal_adapters_grpc_proto_order_proto protoreflect.FileDescriptor

const file_internal_adapters_grpc_proto_order_proto_rawDesc = "" +
	"\n" +
	"(internal/adapters/grpc/proto/order.proto\x12\x05order\"F\n" +
	"\fLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\xd7\x01\n" +
	"\rLoginResponse\x12\x1d\n" +
	"\n" +
	"token_type\x18\x01 \x01(\tR\ttokenType\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x02 \x01(\x03R\texpiresIn\x12!\n" +
	"\faccess_token\x18\x03 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x04 \x01(\tR\frefreshToken\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12\x12\n" +
	"\x04type\x18\x06 \x01(\tR\x04type\x12\x12\n" +
	"\x04code\x18\a \x01(\x05R\x04code\"\xdd\x04\n" +
	"\x12CreateOrderRequest\x12\x19\n" +
	"\bstore_id\x18\x01 \x01(\x03R\astoreId\x12*\n" +
	"\x11merchant_order_id\x18\x02 \x01(\tR\x0fmerchantOrderId\x12%\n" +
	"\x0erecipient_name\x18\x03 \x01(\tR\rrecipientName\x12'\n" +
	"\x0frecipient_phone\x18\x04 \x01(\tR\x0erecipientPhone\x12+\n" +
	"\x11recipient_address\x18\x05 \x01(\tR\x10recipientAddress\x12%\n" +
	"\x0erecipient_city\x18\x06 \x01(\x03R\rrecipientCity\x12%\n" +
	"\x0erecipient_zone\x18\a \x01(\x03R\rrecipientZone\x12%\n" +
	"\x0erecipient_area\x18\b \x01(\x03R\rrecipientArea\x12#\n" +
	"\rdelivery_type\x18\t \x01(\x03R\fdeliveryType\x12\x1b\n" +
	"\titem_type\x18\n" +
	" \x01(\x03R\bitemType\x12/\n" +
	"\x13special_instruction\x18\v \x01(\tR\x12specialInstruction\x12#\n" +
	"\ritem_quantity\x18\f \x01(\x03R\fitemQuantity\x12\x1f\n" +
	"\vitem_weight\x18\r \x01(\x01R\n" +
	"itemWeight\x12*\n" +
	"\x11amount_to_collect\x18\x0e \x01(\x01R\x0famountToCollect\x12)\n" +
	"\x10item_description\x18\x0f \x01(\tR\x0fitemDescription\"}\n" +
	"\x13CreateOrderResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x12\n" +
	"\x04code\x18\x03 \x01(\x05R\x04code\x12$\n" +
	"\x04data\x18\x04 \x01(\v2\x10.order.OrderDataR\x04data\"\xa4\x01\n" +
	"\tOrderData\x12%\n" +
	"\x0econsignment_id\x18\x01 \x01(\tR\rconsignmentId\x12*\n" +
	"\x11merchant_order_id\x18\x02 \x01(\tR\x0fmerchantOrderId\x12!\n" +
	"\forder_status\x18\x03 \x01(\tR\vorderStatus\x12!\n" +
	"\fdelivery_fee\x18\x04 \x01(\x01R\vdeliveryFee\"\x80\x01\n" +
	"\x11ListOrdersRequest\x12'\n" +
	"\x0ftransfer_status\x18\x01 \x01(\x03R\x0etransferStatus\x12\x18\n" +
	"\aarchive\x18\x02 \x01(\x03R\aarchive\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x03R\x05limit\x12\x12\n" +
	"\x04page\x18\x04 \x01(\x03R\x04page\"}\n" +
	"\x12ListOrdersResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x12\n" +
	"\x04code\x18\x03 \x01(\x05R\x04code\x12%\n" +
	"\x04data\x18\x04 \x01(\v2\x11.order.OrdersDataR\x04data\"\xc7\x01\n" +
	"\n" +
	"OrdersData\x12$\n" +
	"\x06orders\x18\x01 \x03(\v2\f.order.OrderR\x06orders\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12!\n" +
	"\fcurrent_page\x18\x03 \x01(\x03R\vcurrentPage\x12\x19\n" +
	"\bper_page\x18\x04 \x01(\x03R\aperPage\x12\"\n" +
	"\rtotal_in_page\x18\x05 \x01(\x03R\vtotalInPage\x12\x1b\n" +
	"\tlast_page\x18\x06 \x01(\x03R\blastPage\"\xdb\b\n" +
	"\x05Order\x120\n" +
	"\x14order_consignment_id\x18\x01 \x01(\tR\x12orderConsignmentId\x12(\n" +
	"\x10order_created_at\x18\x02 \x01(\tR\x0eorderCreatedAt\x12+\n" +
	"\x11order_description\x18\x03 \x01(\tR\x10orderDescription\x12*\n" +
	"\x11merchant_order_id\x18\x04 \x01(\tR\x0fmerchantOrderId\x12%\n" +
	"\x0erecipient_name\x18\x05 \x01(\tR\rrecipientName\x12+\n" +
	"\x11recipient_address\x18\x06 \x01(\tR\x10recipientAddress\x12'\n" +
	"\x0frecipient_phone\x18\a \x01(\tR\x0erecipientPhone\x12!\n" +
	"\forder_amount\x18\b \x01(\x01R\vorderAmount\x12\x1b\n" +
	"\ttotal_fee\x18\t \x01(\x01R\btotalFee\x12 \n" +
	"\vinstruction\x18\n" +
	" \x01(\tR\vinstruction\x12\"\n" +
	"\rorder_type_id\x18\v \x01(\x03R\vorderTypeId\x12\x17\n" +
	"\acod_fee\x18\f \x01(\x01R\x06codFee\x12%\n" +
	"\x0epromo_discount\x18\r \x01(\x01R\rpromoDiscount\x12\x1a\n" +
	"\bdiscount\x18\x0e \x01(\x01R\bdiscount\x12!\n" +
	"\fdelivery_fee\x18\x0f \x01(\x01R\vdeliveryFee\x12!\n" +
	"\forder_status\x18\x10 \x01(\tR\vorderStatus\x12\x1d\n" +
	"\n" +
	"order_type\x18\x11 \x01(\tR\torderType\x12\x1b\n" +
	"\titem_type\x18\x12 \x01(\x03R\bitemType\x12\x1d\n" +
	"\n" +
	"store_name\x18\x13 \x01(\tR\tstoreName\x12.\n" +
	"\x13store_contact_phone\x18\x14 \x01(\tR\x11storeContactPhone\x12\x1d\n" +
	"\n" +
	"cod_amount\x18\x15 \x01(\x01R\tcodAmount\x12'\n" +
	"\x0fdelivery_charge\x18\x16 \x01(\x01R\x0edeliveryCharge\x12\x19\n" +
	"\bstore_id\x18\x17 \x01(\x03R\astoreId\x12%\n" +
	"\x0erecipient_city\x18\x18 \x01(\x03R\rrecipientCity\x12%\n" +
	"\x0erecipient_zone\x18\x19 \x01(\x03R\rrecipientZone\x12%\n" +
	"\x0erecipient_area\x18\x1a \x01(\x03R\rrecipientArea\x12#\n" +
	"\rdelivery_type\x18\x1b \x01(\x03R\fdeliveryType\x12#\n" +
	"\ritem_quantity\x18\x1c \x01(\x03R\fitemQuantity\x12\x1f\n" +
	"\vitem_weight\x18\x1d \x01(\x01R\n" +
	"itemWeight\x12*\n" +
	"\x11amount_to_collect\x18\x1e \x01(\x01R\x0famountToCollect\";\n" +
	"\x12CancelOrderRequest\x12%\n" +
	"\x0econsignment_id\x18\x01 \x01(\tR\rconsignmentId\"W\n" +
	"\x13CancelOrderResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x12\n" +
	"\x04code\x18\x03 \x01(\x05R\x04code\"\x0f\n" +
	"\rLogoutRequest\"R\n" +
	"\x0eLogoutResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x12\n" +
	"\x04code\x18\x03 \x01(\x05R\x04code2\xc8\x02\n" +
	"\fOrderService\x122\n" +
	"\x05Login\x12\x13.order.LoginRequest\x1a\x14.order.LoginResponse\x12D\n" +
	"\vCreateOrder\x12\x19.order.CreateOrderRequest\x1a\x1a.order.CreateOrderResponse\x12A\n" +
	"\n" +
	"ListOrders\x12\x18.order.ListOrdersRequest\x1a\x19.order.ListOrdersResponse\x12D\n" +
	"\vCancelOrder\x12\x19.order.CancelOrderRequest\x1a\x1a.order.CancelOrderResponse\x125\n" +
	"\x06Logout\x12\x14.order.LogoutRequest\x1a\x15.order.LogoutResponseB\x1eZ\x1cinternal/adapters/grpc/protob\x06proto3"

var (
	file_internal_adapters_grpc_proto_order_proto_rawDescOnce sync.Once
	file_internal_adapters_grpc_proto_order_proto_rawDescData []byte
)

func file_internal_adapters_grpc_proto_order_proto_rawDescGZIP() []byte {
	file_internal_adapters_grpc_proto_order_proto_rawDescOnce.Do(func() {
		file_internal_adapters_grpc_proto_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_adapters_grpc_proto_order_proto_rawDesc), len(file_internal_adapters_grpc_proto_order_proto_rawDesc)))
	})
	return file_internal_adapters_grpc_proto_order_proto_rawDescData
}

var file_internal_adapters_grpc_proto_order_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_internal_adapters_grpc_proto_order_proto_goTypes = []any{
	(*LoginRequest)(nil),        // 0: order.LoginRequest
	(*LoginResponse)(nil),       // 1: order.LoginResponse
	(*CreateOrderRequest)(nil),  // 2: order.CreateOrderRequest
	(*CreateOrderResponse)(nil), // 3: order.CreateOrderResponse
	(*OrderData)(nil),           // 4: order.OrderData
	(*ListOrdersRequest)(nil),   // 5: order.ListOrdersRequest
	(*ListOrdersResponse)(nil),  // 6: order.ListOrdersResponse
	(*OrdersData)(nil),          // 7: order.OrdersData
	(*Order)(nil),               // 8: order.Order
	(*CancelOrderRequest)(nil),  // 9: order.CancelOrderRequest
	(*CancelOrderResponse)(nil), // 10: order.CancelOrderResponse
	(*LogoutRequest)(nil),       // 11: order.LogoutRequest
	(*LogoutResponse)(nil),      // 12: order.LogoutResponse
}
var file_internal_adapters_grpc_proto_order_proto_depIdxs = []int32{
	4,  // 0: order.CreateOrderResponse.data:type_name -> order.OrderData
	7,  // 1: order.ListOrdersResponse.data:type_name -> order.OrdersData
	8,  // 2: order.OrdersData.orders:type_name -> order.Order
	0,  // 3: order.OrderService.Login:input_type -> order.LoginRequest
	2,  // 4: order.OrderService.CreateOrder:input_type -> order.CreateOrderRequest
	5,  // 5: order.OrderService.ListOrders:input_type -> order.ListOrdersRequest
	9,  // 6: order.OrderService.CancelOrder:input_type -> order.CancelOrderRequest
	11, // 7: order.OrderService.Logout:input_type -> order.LogoutRequest
	1,  // 8: order.OrderService.Login:output_type -> order.LoginResponse
	3,  // 9: order.OrderService.CreateOrder:output_type -> order.CreateOrderResponse
	6,  // 10: order.OrderService.ListOrders:output_type -> order.ListOrdersResponse
	10, // 11: order.OrderService.CancelOrder:output_type -> order.CancelOrderResponse
	12, // 12: order.OrderService.Logout:output_type -> order.LogoutResponse
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_internal_adapters_grpc_proto_order_proto_init() }
func file_internal_adapters_grpc_proto_order_proto_init() {
	if File_internal_adapters_grpc_proto_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_adapters_grpc_proto_order_proto_rawDesc), len(file_internal_adapters_grpc_proto_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_adapters_grpc_proto_order_proto_goTypes,
		DependencyIndexes: file_internal_adapters_grpc_proto_order_proto_depIdxs,
		MessageInfos:      file_internal_adapters_grpc_proto_order_proto_msgTypes,
	}.Build()
	File_internal_adapters_grpc_proto_order_proto = out.File
	file_internal_adapters_grpc_proto_order_proto_goTypes = nil
	file_internal_adapters_grpc_proto_order_proto_depIdxs = nil
}
